# Generated by Django 4.1.5 on 2023-02-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.PositiveIntegerField(verbose_name='ID Telegram аккаунта')),
                ('link', models.TextField(verbose_name='ID ссылки')),
                ('status', models.PositiveIntegerField(verbose_name='Статус')),
                ('image_link', models.TextField(verbose_name='image link')),
                ('shop', models.TextField(verbose_name='shop')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('product_name', models.TextField(verbose_name='название')),
                ('product_description', models.TextField(verbose_name='описание')),
                ('old_price', models.IntegerField(verbose_name='старая цена')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.PositiveIntegerField(unique=True, verbose_name='ID Telegram аккаунта')),
                ('username', models.TextField(verbose_name='username')),
                ('user_status', models.BooleanField(verbose_name='status')),
                ('authorisation', models.BooleanField(verbose_name='auth')),
                ('status_admin', models.BooleanField(verbose_name='Статус админ')),
                ('online_status', models.BooleanField(verbose_name='Статус онлайн')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
