from django.db import models

# Create your models here.
# Generated by Django 4.1.4 on 2022-12-27 15:57
from skamozon import settings
import datetime

class Profile(models.Model):
    tg_id: models.PositiveIntegerField = models.PositiveIntegerField(
        verbose_name="ID Telegram аккаунта", unique=True
    )

    username: models.TextField = models.TextField(
        verbose_name="username"
        )

    user_status: models.IntegerField = models.BooleanField(
        verbose_name="status"
        )

    authorisation: models.IntegerField = models.BooleanField(
        verbose_name="auth"
        )

    status_admin: models.BooleanField = models.BooleanField(
        verbose_name="Статус админ"
    )

    online_status: models.BooleanField = models.BooleanField(
        verbose_name="Статус онлайн"
        )
    class Meta:
        verbose_name: str = "Профиль"
        verbose_name_plural: str = "Профили"


class Link(models.Model):
    tg_id: models.PositiveIntegerField = models.PositiveIntegerField(
        verbose_name="ID Telegram аккаунта"
    )

    link: models.TextField = models.TextField(
        verbose_name="ID ссылки"
    )

    status: models.PositiveIntegerField = models.PositiveIntegerField(
        verbose_name="Статус"
    )

    image_link: models.TextField = models.TextField(
        verbose_name="image link"
    )

    shop: models.TextField = models.TextField(
        verbose_name="shop"
        )

    price: models.IntegerField = models.IntegerField( 
        verbose_name="цена"
        )

    product_name: models.TextField = models.TextField(
        verbose_name="название"
        )

    product_description: models.TextField = models.TextField(
        verbose_name="описание"
        )

    old_price: models.IntegerField = models.IntegerField(
        "старая цена"
        )
    
    class Meta:
        verbose_name: str = "Ссылка"
        verbose_name_plural: str = "Ссылки"
